### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by CrimsonKoba** [FrictionalGames/AmnesiaTheDarkDescent#17]
[ 20%] Building CXX object core2/CMakeFiles/HPL2.dir/sources/physics/SurfaceData.cpp.o
[ 21%] Building CXX object core2/CMakeFiles/HPL2.dir/sources/physics/VerletParticle.cpp.o
[ 21%] Building CXX object core2/CMakeFiles/HPL2.dir/sources/resources/AnimationManager.cpp.o
[ 21%] Building CXX object core2/CMakeFiles/HPL2.dir/sources/resources/BinaryBuffer.cpp.o
/home/koba/AmnesiaTheDarkDescent/HPL2/core/sources/resources/BinaryBuffer.cpp: In member function 'bool hpl::cBinaryBuffer::CompressAndAdd(char*, size_t, int, bool)':
/home/koba/AmnesiaTheDarkDescent/HPL2/core/sources/resources/BinaryBuffer.cpp:327:46: warning: cast to pointer from integer of different size
[-Wint-to-pointer-cast]
  327 |    int *pSizeDataPtr = (int*)mpData[lStartPos];
      |                                              ^
[ 21%] Building CXX object core2/CMakeFiles/HPL2.dir/sources/resources/BitmapLoaderHandler.cpp.o
[ 21%] Building CXX object core2/CMakeFiles/HPL2.dir/sources/resources/ConfigFile.cpp.o
[ 21%] Building CXX object core2/CMakeFiles/HPL2.dir/sources/resources/EngineFileLoading.cpp.o
[ 21%] Building CXX object core2/CMakeFiles/HPL2.dir/sources/resources/EntFileManager.cpp.o
[ 21%] Building CXX object core2/CMakeFiles/HPL2.dir/sources/resources/EntityLoader_Object.cpp.o
/home/koba/AmnesiaTheDarkDescent/HPL2/core/sources/resources/EntityLoader_Object.cpp: In member function 'virtual hpl::iEntity3D* hpl::cEntityLoader_Object::Load(const tString&, int, bool, hpl::cXmlElement*, const cMatrixf&, const cVector3f&, hpl::cWorld*, const tString&, const tWString&, hpl::cResourceVarsObject*)':
/home/koba/AmnesiaTheDarkDescent/HPL2/core/sources/resources/EntityLoader_Object.cpp:739:74: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
  739 |     if(pEntity->GetEntityType() == "SubMesh" && mpMesh->GetSkeleton() == false && mpMesh->GetAnimationNum() > 0)
      |                                                                          ^~~~~
/home/koba/AmnesiaTheDarkDescent/HPL2/core/sources/resources/EntityLoader_Object.cpp: In member function 'void hpl::cEntityLoader_Object::LoadAndAttachChildren(hpl::cXmlElement*, hpl::iEntity3D*, hpl::cBoneState*, hpl::tEntity3DList&, hpl::tNodeStateMap&, bool, bool)':
/home/koba/AmnesiaTheDarkDescent/HPL2/core/sources/resources/EntityLoader_Object.cpp:936:75: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
  936 |      if(pEntity->GetEntityType() == "SubMesh" && mpMesh->GetSkeleton() == false && mpMesh->GetAnimationNum() > 0)
      |                                                                           ^~~~~
make[2]: *** [core2/CMakeFiles/HPL2.dir/build.make:1727: core2/CMakeFiles/HPL2.dir/sources/resources/EntityLoader_Object.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:290: core2/CMakeFiles/HPL2.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

**Comment by Mudbill** [comment]
You must add the -fpermissive compile flag. See https://github.com/FrictionalGames/AmnesiaTheDarkDescent/pull/2

**Comment by CrimsonKoba** [comment]
> You must add the -fpermissive compile flag. See #2

Thanks
